package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.EmailTarkistus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.20 14:59:20 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class EmailTarkistusTest {



  // Generated by ComTest BEGIN
  /** testTarkistaOsoite28 */
  @Test
  public void testTarkistaOsoite28() {    // EmailTarkistus: 28
    assertEquals("From: EmailTarkistus line: 29", null, tarkistaOsoite("osoite@osoite.fi")); 
    assertEquals("From: EmailTarkistus line: 30", "Osoitteen täytyy sisältää @-merkki", tarkistaOsoite("pspote&osoite.fi")); 
    assertEquals("From: EmailTarkistus line: 31", "Virheellinen sähköpostiosoite", tarkistaOsoite("@gmail.com")); 
    assertEquals("From: EmailTarkistus line: 32", "Liian lyhyt sähköpostiosoite", tarkistaOsoite("m@j.fi")); 
    assertEquals("From: EmailTarkistus line: 33", "Virheellinen sähköpostiosoite", tarkistaOsoite("uusi_osoite@")); 
    assertEquals("From: EmailTarkistus line: 34", "Virheellinen sähköpostiosoite", tarkistaOsoite("1ossa_@osoite.")); 
    assertEquals("From: EmailTarkistus line: 35", null, tarkistaOsoite("12_jee@jee.com")); 
    assertEquals("From: EmailTarkistus line: 36", "Virheellinen sähköpostiosoite", tarkistaOsoite("oso@ite@jee.fi")); 
  } // Generated by ComTest END
}