package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.HetunTarkistus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.21 09:16:16 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HetunTarkistusTest {


  // Generated by ComTest BEGIN
  /** testHetunTarkistusMerkki25 */
  @Test
  public void testHetunTarkistusMerkki25() {    // HetunTarkistus: 25
    assertEquals("From: HetunTarkistus line: 26", 'N', hetunTarkistusMerkki("121212-222")); 
    assertEquals("From: HetunTarkistus line: 27", 'N', hetunTarkistusMerkki("121212-222S")); 
    assertEquals("From: HetunTarkistus line: 28", 'N', hetunTarkistusMerkki("121212-222N")); 
    assertEquals("From: HetunTarkistus line: 29", 'Y', hetunTarkistusMerkki("121212-231Y")); 
    assertEquals("From: HetunTarkistus line: 30", '7', hetunTarkistusMerkki("311212-2317")); 
    assertEquals("From: HetunTarkistus line: 31", '7', hetunTarkistusMerkki("311212-2317XY"));  // vaikka on liikaa merkkejä
    assertEquals("From: HetunTarkistus line: 32", 'F', hetunTarkistusMerkki("999999-9999XY"));  // vaikka on pvm väärin
    try {
    assertEquals("From: HetunTarkistus line: 33", 'N', hetunTarkistusMerkki("12121A-222S")); 
    fail("HetunTarkistus: 33 Did not throw NumberFormatException");
    } catch(NumberFormatException _e_){ _e_.getMessage(); }
    try {
    assertEquals("From: HetunTarkistus line: 34", 'N', hetunTarkistusMerkki("12121A-22")); 
    fail("HetunTarkistus: 34 Did not throw StringIndexOutOfBoundsException");
    } catch(StringIndexOutOfBoundsException _e_){ _e_.getMessage(); }
    try {
    assertEquals("From: HetunTarkistus line: 35", 'N', hetunTarkistusMerkki("121")); 
    fail("HetunTarkistus: 35 Did not throw StringIndexOutOfBoundsException");
    } catch(StringIndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}