package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.TarkistaNimi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.21 13:57:47 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TarkistaNimiTest {



  // Generated by ComTest BEGIN
  /** testTarkistaNimi20 */
  @Test
  public void testTarkistaNimi20() {    // TarkistaNimi: 20
    assertEquals("From: TarkistaNimi line: 21", null, tarkistaNimi("Bridges Sam")); 
    assertEquals("From: TarkistaNimi line: 22", "Syötä sekä suku-, että etunimi", tarkistaNimi("BridgesSam")); 
    assertEquals("From: TarkistaNimi line: 23", null, tarkistaNimi("bridges sam")); 
    assertEquals("From: TarkistaNimi line: 24", "Virheellinen nimi", tarkistaNimi("aa pp")); 
    assertEquals("From: TarkistaNimi line: 25", "Poista ylimääräiset välilyönnit", tarkistaNimi("Huuppa   Alli")); 
    assertEquals("From: TarkistaNimi line: 26", null, tarkistaNimi("Mäki-Aho Pölhö-Kustaa")); 
  } // Generated by ComTest END
}