package kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.16 16:58:21 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KenttaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroiKentta78 */
  @Test
  public void testRekisteroiKentta78() {    // Kentta: 78
    Kentta p1 = new Kentta(); 
    assertEquals("From: Kentta line: 80", 0, p1.getKerhoId()); 
    p1.rekisteroiKentta(); 
    Kentta p2 = new Kentta(); 
    p2.rekisteroiKentta(); 
    int n1 = 1; 
    int n2 = 2; 
    assertEquals("From: Kentta line: 86", n1+1, n2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString200 */
  @Test
  public void testToString200() {    // Kentta: 200
    Kentta k1 = new Kentta(); 
    k1.parse("   1  |  Uusi Golfkerho   | Uusiosoite 2  |  11111 Golfkunta  | 000-1111111 "); 
    assertEquals("From: Kentta line: 203", true, k1.toString().startsWith("1|Uusi Golfkerho|Uusiosoite 2|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta249 */
  @Test
  public void testAseta249() {    // Kentta: 249
    Kentta kentta = new Kentta(); 
    assertEquals("From: Kentta line: 251", null, kentta.aseta(1,"Golfkerho")); 
    assertEquals("From: Kentta line: 252", null, kentta.aseta(2,"Osoite 1")); 
    assertEquals("From: Kentta line: 253", null, kentta.aseta(3,"55555 kunta")); 
  } // Generated by ComTest END
}