package kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.21 10:42:18 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KierroksetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa61 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa61() throws SailoException {    // Kierrokset: 61
    Kierrokset kierrokset = new Kierrokset(); 
    Kierros ki1 = new Kierros(), ki2 = new Kierros(); 
    assertEquals("From: Kierrokset line: 65", 0, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 66", 1, kierrokset.getLkm()); 
    kierrokset.lisaa(ki2); assertEquals("From: Kierrokset line: 67", 2, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 68", 3, kierrokset.getLkm()); 
    assertEquals("From: Kierrokset line: 69", ki1, kierrokset.anna(0)); 
    assertEquals("From: Kierrokset line: 70", ki2, kierrokset.anna(1)); 
    assertEquals("From: Kierrokset line: 71", ki1, kierrokset.anna(2)); 
    assertEquals("From: Kierrokset line: 72", false, kierrokset.anna(1) == ki1); 
    assertEquals("From: Kierrokset line: 73", true, kierrokset.anna(1) == ki2); 
    try {
    assertEquals("From: Kierrokset line: 74", ki1, kierrokset.anna(3)); 
    fail("Kierrokset: 74 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 75", 4, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 76", 5, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 77", 6, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 78", 7, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 79", 8, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 80", 9, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 81", 10, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 82", 11, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 83", 12, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 84", 13, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 85", 14, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 86", 15, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 87", 16, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 88", 17, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 89", 18, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 90", 19, kierrokset.getLkm()); 
    kierrokset.lisaa(ki1); assertEquals("From: Kierrokset line: 91", 20, kierrokset.getLkm()); 
    try {
    kierrokset.lisaa(ki1); 
    fail("Kierrokset: 92 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}