package kerho.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.24 11:11:10 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KierroksetTest {



  // Generated by ComTest BEGIN
  /** testAnnaKierrokset33 
 * @throws SailoException ... */
  @Test
  public void testAnnaKierrokset33() throws SailoException {    // Kierrokset: 33
    Kerho kerho = new Kerho(); 
    Pelaaja p1 = new Pelaaja(), p2 = new Pelaaja(), p3 = new Pelaaja(); 
    p1.rekisteroi(); p2.rekisteroi(); p3.rekisteroi(); 
    int id1 = p1.getpelaajaNro(); 
    int id2 = p2.getpelaajaNro(); 
    Kierros k1 = new Kierros(id1); kerho.lisaa(k1); 
    Kierros k2 = new Kierros(id1); kerho.lisaa(k2); 
    Kierros k3 = new Kierros(id2); kerho.lisaa(k3); 
    Kierros k4 = new Kierros(id2); kerho.lisaa(k4); 
    Kierros k5 = new Kierros(id2); kerho.lisaa(k5); 
    List<Kierros> loytyneet; 
    loytyneet = kerho.annaKierrokset(p3); 
    assertEquals("From: Kierrokset line: 49", 0, loytyneet.size()); 
    loytyneet = kerho.annaKierrokset(p1); 
    assertEquals("From: Kierrokset line: 51", 2, loytyneet.size()); 
    assertEquals("From: Kierrokset line: 52", true, loytyneet.get(0) == k1); 
    assertEquals("From: Kierrokset line: 53", true, loytyneet.get(1) == k2); 
    loytyneet = kerho.annaKierrokset(p2); 
    assertEquals("From: Kierrokset line: 55", 3, loytyneet.size()); 
    assertEquals("From: Kierrokset line: 56", true, loytyneet.get(0) == k3); 
  } // Generated by ComTest END
}