package kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.24 12:16:59 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KierrosTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi105 */
  @Test
  public void testRekisteroi105() {    // Kierros: 105
    Kierros k1 = new Kierros(); 
    assertEquals("From: Kierros line: 107", 0, k1.getKierrosNro()); 
    k1.rekisteroi(); 
    Kierros k2 = new Kierros(); 
    k2.rekisteroi(); 
    int n1 = k1.getKierrosNro(); 
    int n2 = k2.getKierrosNro(); 
    assertEquals("From: Kierros line: 113", n1+1, n2); 
  } // Generated by ComTest END
}