package kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.21 10:13:14 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KierrosTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi60 */
  @Test
  public void testRekisteroi60() {    // Kierros: 60
    Kierros k1 = new Kierros(); 
    assertEquals("From: Kierros line: 62", 0, k1.getkierrosNro()); 
    k1.rekisteroi(); 
    Kierros k2 = new Kierros(); 
    k2.rekisteroi(); 
    int n1 = k1.getkierrosNro(); 
    int n2 = k2.getkierrosNro(); 
    assertEquals("From: Kierros line: 68", n1+1, n2); 
  } // Generated by ComTest END
}