package kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.24 10:58:04 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PelaajaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi86 */
  @Test
  public void testRekisteroi86() {    // Pelaaja: 86
    Pelaaja p1 = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 88", 0, p1.getpelaajaNro()); 
    p1.rekisteroi(); 
    Pelaaja p2 = new Pelaaja(); 
    p2.rekisteroi(); 
    int n1 = p1.getpelaajaNro(); 
    int n2 = p2.getpelaajaNro(); 
    assertEquals("From: Pelaaja line: 94", n1+1, n2);  //
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroiOsake108 */
  @Test
  public void testRekisteroiOsake108() {    // Pelaaja: 108
    Pelaaja p1 = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 110", 0, p1.getOsakeNro()); 
    p1.rekisteroiOsake(); 
    Pelaaja p2 = new Pelaaja(); 
    p2.rekisteroiOsake(); 
    int n1 = 1; 
    int n2 = 2; 
    assertEquals("From: Pelaaja line: 116", n1+1, n2); 
  } // Generated by ComTest END
}