package kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.21 09:13:55 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PelaajatTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa35 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa35() throws SailoException {    // Pelaajat: 35
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja aku1 = new Pelaaja(), aku2 = new Pelaaja(); 
    assertEquals("From: Pelaajat line: 39", 0, pelaajat.getLkm()); 
    pelaajat.lisaa(aku1); assertEquals("From: Pelaajat line: 40", 1, pelaajat.getLkm()); 
    pelaajat.lisaa(aku2); assertEquals("From: Pelaajat line: 41", 2, pelaajat.getLkm()); 
    pelaajat.lisaa(aku1); assertEquals("From: Pelaajat line: 42", 3, pelaajat.getLkm()); 
    assertEquals("From: Pelaajat line: 43", aku1, pelaajat.anna(0)); 
    assertEquals("From: Pelaajat line: 44", aku2, pelaajat.anna(1)); 
    assertEquals("From: Pelaajat line: 45", aku1, pelaajat.anna(2)); 
    assertEquals("From: Pelaajat line: 46", false, pelaajat.anna(1) == aku1); 
    assertEquals("From: Pelaajat line: 47", true, pelaajat.anna(1) == aku2); 
    try {
    assertEquals("From: Pelaajat line: 48", aku1, pelaajat.anna(3)); 
    fail("Pelaajat: 48 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    pelaajat.lisaa(aku1); assertEquals("From: Pelaajat line: 49", 4, pelaajat.getLkm()); 
    pelaajat.lisaa(aku1); assertEquals("From: Pelaajat line: 50", 5, pelaajat.getLkm()); 
    try {
    pelaajat.lisaa(aku1); 
    fail("Pelaajat: 51 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}