package kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.18 11:37:26 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PelaajaTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi51 */
  @Test
  public void testRekisteroi51() {    // Pelaaja: 51
    Pelaaja p1 = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 53", 0, p1.getpelaajaNro()); 
    p1.rekisteroi(); 
    Pelaaja p2 = new Pelaaja(); 
    p2.rekisteroi(); 
    int n1 = p1.getpelaajaNro(); 
    int n2 = p2.getpelaajaNro(); 
    assertEquals("From: Pelaaja line: 59", n1+1, n2);  //
  } // Generated by ComTest END
}